### ISSUE TITLE
RTW_COMMAND_THREAD taking large amounts of processor time after 1.6.0 update

### ISSUE THREAD

**Issue by Ken6432** [QIDITECH/QIDI_PLUS4#32]
After updating to the  1.6.0 firmware, I started getting MTU errors when trying to print as well as during prints.  In investigation with the help of Stew675 found that the RTW_COMMAND_THREAD was taking the majority of the CPU time.

After pulling the wifi dongle, the printer behaved more like prior to the update.  Response time was better and I was able to start a print.

There is another possibly unrelated issue that I will log separately that kept my print from completing.

**Comment by QIDITECH** [comment]
We cannot reproduce the problem, please restart the printer and try again.
The 1.6.0 firmware should not have any effect on this, have you installed any other plugins or programs?

**Comment by Ken6432** [comment]
I have stopped and started the printer numerous times.  I have not installed any other software at the OS level, though I have some extra config in some of the cfg files.  I backed most (if not all) of that out during debugging though.

I'll ask on the Discord if anyone else that upgraded has seen this.

Out of curiosity, did you test while connected via Ethernet?  That is my situation.  Perhaps there is some sort of odd interaction with the wifi driver code you made and using Ethernet.

Thanks for the help.

**Comment by stew675** [comment]
@QIDITECH I was assisting Ken with his issue on the Discord server.  The exact reproduction steps were:

1) Configure printer network to be in wired ethernet LAN mode only.
2) The Wifi Module is unconfigured but left plugged in
3) Upgrade to v1.6.0
4) Observe that the kernel RTW_CMD_THREAD is consuming 100% of one CPU core

Issue was resolved for Ken by unplugging the Wifi dongle, which deactivates the kernel thread.

**Comment by QIDITECH** [comment]
Thank you for your cooperation.
This issue does exist, we will fix it in the next version.

**Comment by hnatloz** [comment]
After 1.6.0 update it stopped working.
Dear Qidi, I need your help.
I updated the plus 4 software today, of course Fluidd didn't work for me either, and since I didn't read this topic then I started updating everything else, using ssh terminal. Currently it doesn't respond to any commands :(
What should I do? Is there a factory image for a restore?
Thanks in advance for your help

**Comment by QIDITECH** [comment]
@hnatloz Have you installed octoeverywhere or other plugins? Please refer to #37.

**Comment by dssamusaran** [comment]
Machine stopped working as well after 1.6.0, fluidd is completely dead. Network is OK for ping/ssh.
I did not install any plugin and never connected through SSH even once.
My machine is completely stock setup...

I already tried the recovery procedure from this page https://wiki.qidi3d.com/en/PLUS4/Manual/firmware-update
It is still not working.

So I contacted support and explained all I tried, including the msscreen.recovery from the wiki.

And they sent me the exact same procedure and file (I compared through an md5 checksum)

It looks like 1.6.0 is botched and needs a quick fix for quite a bunch of people. @QIDITECH  we really all need your help!

**Comment by QIDITECH** [comment]
You mentioned in the other question that you use octoAPP, right?
You should refresh the SOC file instead of the msscreen.

**Comment by dssamusaran** [comment]
Yes I confirm I use octoapp but I did not install the companion plug-ins on the machine. So only basic features and machine was 'stock'.

I did the SOC refresh with the mksclient.recovery file multiple times as well and it's still not coming back to life.

I'll try removing the wifi dongle to see if it helps.

**Comment by QIDITECH** [comment]
Please try to refresh emmc. We have sent you the detailed operation through after-sales email, please check your email.

**Comment by dssamusaran** [comment]
I had some news today from support. 
They basicaly do not know what happened with some updates and they're going to send a new emmc to replace the old one.

Quite a drastic mesure but I guess it'll work and get the machine back up and running.

**Comment by QIDITECH** [comment]
@hnatloz  We are very sorry, we have repeatedly tested on multiple devices, but the problem still cannot be repeated, please refer to the link below to try to update emmc, or contact after-sales service.
https://wiki.qidi3d.com/en/Memo/flash-emmc

**Comment by Ken6432** [comment]
@QIDITECH - When is a fix to 1.6.0 planned?  It surprises me that with the known issues there have been, the a quick fix has not been supplied by now.

**Comment by Ken6432** [comment]
@QIDITECH - When is a fix to 1.6.0 planned?  It surprises me that with the known issues there have been, the a quick fix has not been supplied by now.

**Comment by snigel** [comment]
Can confirm that `RTW_CMD_THREAD` is consuming a lot of CPU on 1.6.0.
